services:
  configserver:
    image: "lokesh874/configserver:m1"
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: "configserver-ms"
    ports:
      - "8888:8888"
    healthcheck:
      test: "curl --fail --silent localhost:8888/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - lokesh-school
    deploy:
      resources:
        limits:
          memory: 700m

  discoveryserver:
    image: "lokesh874/discoveryserver:m1"
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: "discovery-ms"
    ports:
      - "8761:8761"
    healthcheck:
      test: "curl --fail --silent localhost:8761/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8888/"
      SPRING_APPLICATION_NAME: "discoveryserver"
    networks:
      - lokesh-school
    deploy:
      resources:
        limits:
          memory: 700m

  students:
    image: "lokesh874/students:m1"
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: "students-ms"
    ports:
      - "8090:8090"
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      configserver:
        condition: service_healthy
      discoveryserver:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8888/"
      SPRING_APPLICATION_NAME: "students"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discoveryserver:8761/eureka/"
    networks:
      - lokesh-school
    deploy:
      resources:
        limits:
          memory: 700m


  schools:
    image: "lokesh874/schools:m1"
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: "schools-ms"
    ports:
      - "8070:8070"
    depends_on:
      configserver:
        condition: service_healthy
      discoveryserver:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8888/"
      SPRING_APPLICATION_NAME: "schools"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discoveryserver:8761/eureka/"
    networks:
      - lokesh-school
    deploy:
      resources:
        limits:
          memory: 700m


  gatewayserver:
    image: "lokesh874/gatewayserver:m1"
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: "gatewayserver-ms"
    ports:
      - "8222:8222"
    depends_on:
      configserver:
        condition: service_healthy
      discoveryserver:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8888/"
      SPRING_APPLICATION_NAME: "gatewayserver"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8761/eureka/"
    restart: always
    networks:
      - lokesh-school


networks:
  lokesh-school:
    driver: "bridge"
