eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/students/**
        - id: schools
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/schools/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true
  tracing:
    sampling:
      probability: 1.0

info:
  app:
    name: "gatewayserver"
    description: "Gateway Server Application"
    version: "1.0.0"
