#server:
#  port: 8888
#
#spring:
#  profiles:
#    active: native
#  application:
#    name: configserver
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/configurations


spring:
  application:
    name: "configserver"
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/M-Lokesh/lokesh-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
server:
  port: 8888

